server:
  port: 8080

spring:
  application:
    name: template

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/${DB_NAME:template_app}
    username: template_app
    password: password

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
