server:
  port: 8080

spring:
  application:
    name: template

  datasource:
    url: jdbc:postgresql://localhost:15432/template_app
    username: template_app
    password: password

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
